# Generated by Django 4.1.7 on 2023-03-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('EUR', models.FloatField(default=1.0)),
                ('USD', models.FloatField(default=1.0)),
                ('CNY', models.FloatField(default=1.0)),
                ('GBP', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
