# Generated by Django 4.1.7 on 2023-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='Date'),
        ),
    ]
