# Generated by Django 4.1.7 on 2023-03-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rename_date_currency_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-Date']},
        ),
    ]
