# Generated by Django 4.1.7 on 2023-03-28 21:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Transaction Timestamp')),
                ('description', models.CharField(max_length=100)),
                ('expense', models.CharField(default='Empty', max_length=300, null=True)),
                ('revenue', models.CharField(default='Empty', max_length=300, null=True)),
                ('asset', models.CharField(default='Empty', max_length=300, null=True)),
                ('liability', models.CharField(default='Empty', max_length=300, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
