# Generated by Django 4.1.7 on 2023-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=100)),
                ('DateTime', models.DateTimeField(verbose_name='Transaction Timestamp')),
                ('description', models.CharField(max_length=100)),
                ('expense', models.CharField(default='Empty', max_length=300, null=True)),
                ('revenue', models.CharField(default='Empty', max_length=300, null=True)),
                ('asset', models.CharField(default='Empty', max_length=300, null=True)),
                ('liability', models.CharField(default='Empty', max_length=300, null=True)),
            ],
        ),
    ]
