# Generated by Django 4.1.7 on 2023-03-24 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Transaction Timestamp'),
        ),
    ]
