# Generated by Django 4.1.7 on 2023-03-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_user_id_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='liability',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='revenue',
        ),
        migrations.AddField(
            model_name='transaction',
            name='detail',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
